### ISSUE TITLE
ReactCameraView cannot be cast to ViewGroup

### ISSUE THREAD

**Issue by JorisM** [timmh/react-native-camera#2]
I get the following error when running the example:

![screenshot_2015-10-09-08-44-15](https://cloud.githubusercontent.com/assets/294174/10398794/407a9f46-6eaf-11e5-8a50-dda7423236a3.png)

any idea as to why this happens?

**Comment by timmh** [comment]
My first thought was that this might be caused by adding other views as subviews of the camera-view but this seems to work for me.
If you would share the relevant render method I could try to replicate this myself and take a deeper look.
You can also run the [exaple project](https://github.com/timmh/react-native-camera/tree/master/example) I just pushed and try if you have the same issue with that.

**Comment by JorisM** [comment]
It works now! I tried the example project, and then figured out that I imported the wrong package in my MainActivity.

Thanks!
